#!/usr/bin/env bash
fa-to-bed() {
  # Create BED intervals which span each contig in a FASTA file
  if [[ -z $1 ]]; then print "USAGE: fa-to-bed <FASTA>"; return 1; fi
  bioawk -c fastx '{ print $name"\t0\t"length($seq) }' "${1}"
}
