#!/usr/bin/env bash
function lscolors {
  # Display a list of supported colors
  # https://github.com/jleclanche/dotfiles
  ((cols = $COLUMNS - 4))
  s=$(printf %${cols}s)
  for i in {000..$(tput colors)}; do
    echo -e "${i}" $(tput setaf "${i}"; tput setab "${i}")${s// /=}$(tput op);
  done
}
