#!/usr/bin/env bash
export PATH=$HOME/bin:/usr/local/bin:$PATH
export ZSH=/home/${whoami}/.oh-my-zsh
#export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

plugins=(
  archlinux
  battery
  colored-man-pages
  aws
  git
  ssh-agent
  systemd
)

fpath=( "${HOME}/.zfunctions" $fpath )

source "${ZSH}/oh-my-zsh.sh"
source /etc/profile
source <( cat ~/.dotfiles/bash-functions/* )

# USER CONFIGURATION ##########################################################

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nano'
else
  export EDITOR='nano'
  export VISUAL='subl3'
fi

# If fzf is installed use those key-bindings and completions
if [[ -d /usr/share/fzf/ ]]; then
  source /usr/share/fzf/key-bindings.zsh
  source /usr/share/fzf/completion.zsh
fi

zstyle :omz:plugins:ssh-agent agent-forwarding on
zstyle :omz:plugins:ssh-agent identities github cv-sandbox.pem

# ALIASES #####################################################################

alias zshconfig="${EDITOR} ~/.zshrc"
alias ohmyzsh="${EDITOR} ~/.oh-my-zsh"

alias cd..='cd ..'
alias cp='cp -i'
alias d='ls'
alias df='df -h -x supermount'
alias du='du -h'
alias egrep='egrep --color'
alias fgrep='fgrep --color'
alias grep='grep --color'

alias ls='ls -lhF --color=auto'
alias l='ls -lhF --color=auto '
alias la='ls -lhFa --color=auto'
alias lt='ls -lhFt --color=auto'
alias ld='ls -lhFd */ --color=auto'
alias lta='ls -lhFta --color=auto'
alias ltd='ls -lhFtd --color=auto'

alias md='mkdir'
alias mv='mv -i'
alias p='cd -'
alias rd='rmdir'
alias rm='rm -i'

alias less='less -SF -# 15'

alias .=source

alias igv='igv > /dev/null 2>&1 &'
alias xclip='xclip -selection c'

alias cls=clear
alias w3m='w3m -o ext_image_viewer=0'

# BINDKEYS ####################################################################

# bindkey '^[[6~  page down
# bindkey '^[[2~  insert

bindkey '^[[5~' beginning-of-history
bindkey '^[[H'  beginning-of-line
bindkey '^[[3~' delete-char
bindkey '\e[8'  end-of-line

# mappings for making up and down arrow searching through history:
bindkey '\e[A' history-search-backward
bindkey '\e[B' history-search-forward
bindkey '\e[C' forward-char
bindkey '\e[D' backward-char

# Use [Tab] and [Shift]+[Tab] to cycle through all the possible completions:
bindkey '\t'  menu-complete
bindkey '\e[Z' menu-complete-backward

# HISTORY #####################################################################

HISTCONTROL=ignoredups
export HISTFILESIZE=20000
export HISTSIZE=100000
export HISTIGNORE="&:ls:[bf]g:exit"

# PROMPT ######################################################################

autoload -U promptinit; promptinit
prompt pure
