#!/usr/bin/env bash
aws3du() {
  # Get the total size and number of objects of an S3 URI
  # https://gist.github.com/hrwgc/3fedab87eb937772ca58
  # From https://gist.github.com/hrwgc/3fedab87eb937772ca58
  if [[ -z $1 ]]; then print "USAGE: aws3du <S3URI>"; return 1; fi
  bucket=`cut -d/ -f3 <<< $1`
  prefix=`awk -F/ '{for (i=4; i<NF; i++) printf $i"/"; print $NF}' <<< $1`
  aws s3api \
    list-objects \
    --bucket $bucket \
    --prefix=$prefix \
    --output text \
    --query '[sum(Contents[].Size), length(Contents[])]' \
    | while read -r size num_objects; do
      jq '. |{ size:.[0],num_objects: .[1]}' <<< "[\"$(numfmt --to=si ${size})\",${num_objects}]"
     done
}
