#!/usr/bin/env python3
import random
from datetime import datetime
from twinstrand_bots import Bot
from seattle_food_truck import Location, SeattleFoodTruckClient

INTRODUCTIONS = [
    'I swear I never get tired of listing trucks:',
    'These are your glorious food truck options:',
    'Fancy a lunch at these food trucks?',
    'Here are your exciting truck lunch options:',
    'Maybe today is the day you hit up a truck with a coworker?',
    'If I was a human I would eat here:',
    'LunchTruckBot here, serving you daily:',
    'Lunch trucks today:',
]


def datestamp():
    now = datetime.now()

    if 11 <= now.day <= 13:
        suffix = 'th'
    else:
        suffix = {1: 'st', 2: 'nd', 3: 'rd'}.get(now.day % 10, 'th')

    return now.strftime('%A %b {S}').replace('{S}', str(now.day) + suffix)


def todays_truck_message(location_uid, botname, endpoint):

    message = f'*{datestamp()}*\n'

    bot = Bot(botname)

    client = SeattleFoodTruckClient()
    client.location = Location({'uid': location_uid})
    trucks = client.trucks_today()

    if len(trucks) == 0:
        message += 'There are no food trucks scheduled for today! :dizzy_face:'
    else:
        message += f'{random.choice(INTRODUCTIONS)}\n'
        for i, truck in enumerate(trucks):
            message += f'\t{i+1}. {truck.name} — _{truck.food_description}_\n'

    call = bot.post_message(endpoint=endpoint, message=message)
    return call


if __name__ == '__main__':
    call = todays_truck_message(
        location_uid=69,
        botname='lunchtruckbot',
        endpoint='#lunch')
